### ISSUE TITLE
client error: (450) Blocked by Windows Parental Controls (Microsoft)

### ISSUE THREAD

**Issue by englianhu** [soodoku/abbyyR#1]
``` diff
> library('EBImage')
> library('abbyyR')

> lnk <- 'http://www.theage.com.au/ffximage/2005/07/22/id_card1_gallery__502x329,0.jpg'
> pic <- readImage(lnk)
> display(pic)

> download.file(lnk,destfile=paste0(getwd(),'/pic.jpg'))
--2015-11-03 18:23:39--  http://www.theage.com.au/ffximage/2005/07/22/id_card1_gallery__502x329,0.jpg
Resolving www.theage.com.au (www.theage.com.au)... 104.86.110.66, 104.86.110.27
Connecting to www.theage.com.au (www.theage.com.au)|104.86.110.66|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23154 (23K) [image/jpeg]
Saving to: ‘/home/ryoeng/pic.jpg’
     0K .......... .....
> setapp(c('cloud_ocr', 'PgUbJEeFzlKMjeX/668puVFZ'))
> processPhotoId(file_path=paste0(getwd(),'/pic.jpg'), idType='auto', imageSource='auto')
..... ..                              100% 19.2M=0.001s
2015-11-03 18:23:39 (19.2 MB/s) - ‘/home/ryoeng/pic.jpg’ saved [23154/23154]
- Error in processPhotoId(file_path = paste0(getwd(), "/pic.jpg"), idType = "auto",  : 
-   client error: (450) Blocked by Windows Parental Controls (Microsoft)
> 
> file.remove(paste0(getwd(),'/pic.jpg'))
[1] TRUE
```

Just curous that is there any connection of your apps related to Microsoft since abbyyR is a web-base application I though? Any solution?

**Comment by soodoku** [comment]
thanks for this. 

i have been able to come up with a hack for the problem but let me come up with a solution. otherwise will ping you with the hack.

**Comment by soodoku** [comment]
Two things:
a. http://ocrsdk.com/documentation/apireference/processPhotoId/ is still being 'tested' and performance and support are poor. So two things:
1) The ID pic you linked to for instance produces this garbage: 
https://ocrsdk.blob.core.windows.net/files/575fadee-fe62-454a-b328-628c6bedfaac.result?sv=2012-02-12&se=2015-11-05T00%3A00%3A00Z&sr=b&si=downloadResults&sig=6PwxctX854feHUv3df0zKRQWdVFQsH7TYiQIU0vIALQ%3D
2) The API doesn't like queries (additional params) being submitted so in the github version query being submitted has been set to NULL. And it works then. See above, for instance.
b. 450 status code is issued by abbyy for other reasons. It is interpreted by httr as this firewall code. In the latest version on github, that has been fixed. I will map all the status codes to abbyy status codes in future versions.

I will look more into it but hope this is useful for you.
