### ISSUE TITLE
trouble using ocrFile()

### ISSUE THREAD

**Issue by ageyl** [soodoku/abbyyR#4]
I'm attempting to use the ocrFile() function to read pdf image of a table. If I use Abbyyr's "finreaderonline.com" with my pdfs I get a nice .csv table back.

When I use ocrFile() I get the following error message:
`
Error in Ops.factor(res$id, listFinishedTasks()$id) : 
  level sets of factors are different
`

If I run getAppInfo() 
`getAppInfo()
Name of Application: 1
No. of Pages Remaining: 1
No. of Fields Remaining: 1
Application Credits Expire on: 1
Type: 1`

Any ideas about what I could check?

**Comment by soodoku** [comment]
Interesting. Let me investigate.

**Comment by soodoku** [comment]
Apologies for the long delay. I believe the error you are getting is caused by the presence of factors instead of character vector. I have coerced to char as a fix. 
Ping me if the latest version of abbyyR still gives you problems.
