### ISSUE TITLE
File name in downloaded files using getResults()

### ISSUE THREAD

**Issue by abhy3** [soodoku/abbyyR#5]
The name of the downloaded files are the IDs of the file in listTasks(). Names are not meaningful and does not contain the file extension. Is there any way to keep the name of files in the 'description' as stored in the sample C# app below:
http://ocrsdk.com/documentation/code-samples/dotNet.zip

Then the name can be taken from description and extension could be appended against each file.

**Comment by soodoku** [comment]
Thanks for bringing this up. I remember spending some time exploring this when I first wrote the client, but couldn't come up with a good way. So I implemented the following:

The getResults() function returns a data.frame which appends file paths to listFinishedTasks: https://github.com/soodoku/abbyyR/blob/master/R/getResults.R

See if that is of use to you. I will investigate also. Feel free to PR also.
